name: Publish nuget

on:
  workflow_dispatch:

  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'
      - '[0-9]+.[0-9]+.[0-9]+-preview[0-9]+'

env:
  NUGET_PACKAGES: ${{ github.workspace }}/.nuget/packages
  BUILD_CONFIG: 'Release'
  SOLUTION_FILE: './src/MoonlyBird.InMemoryEventBus.sln'
  PROJECT_FILE: './src/MoonlyBird.InMemoryEventBus/MoonlyBird.InMemoryEventBus.csproj'
  BUILD_OUTPUT_FOLDER: './src/MoonlyBird.InMemoryEventBus/bin/Release'
  PROJECT_NAME: 'MoonlyBird.InMemoryEventBus'
  CACHE_NAME: package-nuget

jobs:
  build:
    name: Build and test solution
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
          cache: true
      
      - name: Restore dependencies
        run: dotnet restore ${{ env.SOLUTION_FILE }} --locked-mode
      
      - name: Build
        run: dotnet build ${{ env.SOLUTION_FILE }} --nologo --configuration ${{ env.BUILD_CONFIG }} --no-restore /property:Version=${{ github.ref_name}}
      
      - name: Test
        run: dotnet test ${{ env.SOLUTION_FILE}} /p:Configuration=${{ env.BUILD_CONFIG }} --no-restore --no-build --verbosity normal

      - name: Save nupkg into cache
        uses: actions/cache/save@v4
        with:
          path: ${{ env.BUILD_OUTPUT_FOLDER }}
          key: ${{ runner.os }}-${{ env.CACHE_NAME }}-build-${{ env.PROJECT_NAME }}.${{ github.ref_name }}

  publish:
    environment: 'nuget-registry'
    name: publish nuget package - Common
    runs-on: ubuntu-22.04
    needs: [ build ]
    steps:
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
      - name: Restore cache of build
        uses: actions/cache/restore@v4
        with:
          path: ${{ env.BUILD_OUTPUT_FOLDER }}
          key: ${{ runner.os }}-${{ env.CACHE_NAME }}-build-${{ env.PROJECT_NAME }}.${{ github.ref_name }}
      - name: Publish on nuget.org
        run: dotnet nuget push ${{ env.BUILD_OUTPUT_FOLDER }}/${{ env.PROJECT_NAME }}.${{ github.ref_name }}.nupkg --api-key ${{ secrets.NUGET_API_KEY }} -s https://api.nuget.org/v3/index.json
        
